### ISSUE TITLE
formula in 1.7.5

### ISSUE THREAD

**Issue by performantdata** [winitzki/sofp#13]
The first formula, `\int_0^x \frac{dx}{1+x}` doesn't make sense, reusing _x_ as the integration variable.

**Comment by winitzki** [comment]
Yes, it is confusing, but math books use that notation frequently. This confustion is quite similar to what would happen if you write code such as `{ x => x => 2 }`. The inner `x` is meant to be a different variable than the shadowed outer `x`; these two variables just happen to have the same name.
