### ISSUE TITLE
References/links to archive.is are dead

### ISSUE THREAD

**Issue by Jiehong** [winitzki/sofp#18]
Hi,

Multiple references as footnotes are dead links.

For example, page 571, "40-year gap hypothesis" as a ref. number 37: http://archive.is/rJc4A

But this link is dead.

Ref. number 36 on that same page is also an archive.is link, and is equally dead.

I'm afraid most of them are.

**Comment by winitzki** [comment]
Hi,

I'm not sure why you say it's dead. I can click on that link and see the page. Here is a screenshot:
<img width="939" alt="Screen Shot 2020-09-04 at 7 03 17 PM" src="https://user-images.githubusercontent.com/2163489/92267744-02efda80-ee96-11ea-9153-7794c423f274.png">

**Comment by Jiehong** [comment]
@winitzki,

I investigated, and I've found out why:

```sh
$ nslookup www.archive.today 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find www.archive.today: SERVFAIL
```

```sh
slookup www.archive.today 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.archive.today
Address: 188.143.233.210
Name:	www.archive.today
Address: 2001:470:1f15:79a::acfd:e04
Name:	www.archive.today
Address: 2001:470:1f15:79a::5f5a:c500
```

So, it seems that archive.is is not resolvable from cloudflare DNS servers. [Wikipedia confirms this](https://en.wikipedia.org/wiki/Archive.today#Worldwide).

Any reasons/differences with using archive.is instead of archive.org? (ex: https://web.archive.org/web/20200905075949/https://www.linkedin.com/pulse/40-year-gap-what-has-academic-computer-science-ever-done-winitzki/)

**Comment by winitzki** [comment]
Short URLs are the only reason I'm using archive.is, and also I did not make sure that all links exist on archive.org.

Do you have a solution for this problem? How to create a short URL for archive.org? If you want to contribute archive.org links or other short links that work better, I'd appreciate your help. Post them here and I'll incorporate them into the book. Thank you!

**Comment by Jiehong** [comment]
I was unable to have short urls from archive.org (they don't seem to offer this at all).

In the end, I don't have a solution for this then.
