### ISSUE TITLE
Set up Circle CI or other free CI for building the book from sources

### ISSUE THREAD

**Issue by winitzki** [winitzki/sofp#20]
At the moment, the only way to build the PDF book is to run `bash make_sofp_pdf.sh` on a Mac where specific software is installed (LyX, pdftk, hunspell).

It is better if the book is compiled automatically by CI. This requires installing LyX, pdfLaTeX, and pdftk, before running the build scripts in CI. Bonus is to install hunspell and verify spell checking.

Also, if the Scala code examples can be verified, some jvm and scala packages will be required.

All that could be configured using yaml for circle-ci.

**Comment by leobenkel** [comment]
I use Travis usually, i wrote a tutorial: https://leobenkel.com/2019/09/travis-continuous-deployment/ , it is pretty straightforward usually.

**Comment by winitzki** [comment]
Thank you @leobenkel - I will take a look. But right now I have no time to set up Travis, this will have to wait.

**Comment by leobenkel** [comment]
I am very busy as well but if I find some time, I'll try to set it up.

**Comment by FranklinChen** [comment]
How about GitHub Actions? I haven't had time to migrate my own stuff away from Travis to that yet, but it's on my to-do list...

**Comment by winitzki** [comment]
I don't know but if you have any experience with the new Github Actions, please tell me.

**Comment by barisere** [comment]
@winitzki I have some experience with GitHub Actions, but I don't have any experience with the tools used to build the book or to check Scala code. I can give it a try though.

**Comment by winitzki** [comment]
To build the book, the minimum is 1) install LyX  and LaTeX, 2) run commands:
```bash
lyx --export pdflatex sofp.lyx
pdflatex sofp.tex
makeindex sofp.idx
pdflatex sofp.tex
```

Once you get that working, let me know ;)

**Comment by barisere** [comment]
@winitzki Using the sequence of command lines above I get the following error
```
LaTeX Warning: Command \: invalid in math mode on input line 3603.

! Argument of \gunderline has an extra }.
<inserted text>
                \par
l.3603 \end{align*}

?
! Emergency stop.
<inserted text>
                \par
l.3603 \end{align*}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on sofp.log.
```
I then tried using `make_sofp_pdf.sh` instead. It ran until `makeindex` and produced the following error.
```
Result is sofp.pdf, size 6231196 bytes, with 648 pages.
        makeindex "$base.idx"
Draft page ranges 1-424 592-615 621-end
Error: Draft file has 476 pages instead of expected 468. Please check.
Checking page counts...
Error: Chapter Mathematical formulas as code. I. should have 17 pages but has 18 pages instead.
Error: Chapter Mathematical formulas as code. II. should have 42 pages but has 43 pages instead.
Error: Chapter The logic of types. I. should have 34 pages but has 35 pages instead.
Error: Chapter The logic of types. II. should have 24 pages but has 25 pages instead.
Error: Chapter Reasoning about code. should have 12 pages but has 13 pages instead.
Error: Chapter Typeclasses and functions of types should have 63 pages but has 64 pages instead.
Error: Chapter Computations in functor blocks. I. should have 54 pages but has 55 pages instead.
Error: Chapter Computations in functor blocks. II. should have 63 pages but has 64 pages instead.
Error: Chapter Traversable functors and profunctors should have 6 pages but has -436 pages instead.
Error: Chapter ``Free'' type constructions should have 18 pages but has 460 pages instead.
Error: Chapter Computations in functor blocks. III. should have 129 pages but has 128 pages instead.
Error: Chapter Summary and problems should have 4 pages but has -588 pages instead.
Error: Chapter ``Applied functional type theory'': A proposal should have 5 pages but has 597 pages instead.
Done.
Checking spelling with hunspell...
Found 33 misspelled_words.
```
I don't know how to proceed (I don't know anything about Tex), but I think we are close. If I can build this on Linux, then I can proceed to configure GitHub Actions for it.

**Comment by winitzki** [comment]
@barisere Let me push a change so that at least the plain commands work:

```bash
rm  sofp-*.tex
lyx --export pdflatex sofp.lyx
pdflatex sofp.tex
makeindex sofp.idx
pdflatex sofp.tex
```

This should create a PDF file.

Please let me know if this works for you after the latest changes in the repository (master branch).

**Comment by barisere** [comment]
@winitzki This works.

**Comment by winitzki** [comment]
@barisere The errors from running `make_sofp_pdf.sh` are not very important; they are saying that the page formatting is not as expected, so the number of pages is not equal to what I have on my Mac. Maybe this indicates some error that we can fix later.

**Comment by barisere** [comment]
@winitzki I'm sorry that I'm slow on this, I've been busy with work and my time management has slipped lately.
Besides building the book, what else should the setup do?

- [ ] Release a new version of the book if the entire pipeline succeeds?

- [ ] Open an issue with relevant log files if the pipeline fails, or just place the log files somewhere we can access?

I have created a minimal setup on my fork of this repo. The CI job runs as expected using the command lines above. I'm not using `make_sofp_pdf.sh` yet, we'll make some edits to that.
The current setup runs the CI job, builds the book and uploads the PDF file as an artefact that we can download. If the build step fails, it tries to upload the `sofp.log` and `mispelled_words` files.
You can view the current setup here: https://github.com/barisere/sofp/actions/runs/283488721.
I'll create a pull request once we get something more satisfactory.

##### Caveat
The current setup depends on my Docker hub repository to speed up the CI job by using a pre-built image. We'll need to switch that to your own account. We can host the image on GitHub using their package registry.

**Comment by winitzki** [comment]
Hi @barisere ,
Thank you for doing this work. Looks like we are close to something working. 

I'm not familiar enough with github actions. What I think needs to be done is:

- The CI pipeline should run whenever a merge to master branch occurs. I don't know how to set this up.
- The CI pipeline should publish new file as a release, and do nothing on failure. I'm not sure if github actions have a standard place that shows logs; if so, it's sufficient to be able to see them.
- The CI pipeline should use a bash script containing the commands to build the pdf file, rather than having those commands  directly embedded in a Dockerfile or somewhere else.

I'd appreciate if you help me further with this!

Please let me know how I can get the github to host the docker image for this build. I would expect to have a large image since it needs to contain LaTeX and LyX.

Thank you again! 
Sergei

**Comment by barisere** [comment]
Hi @winitzki.
Thank you too for putting out such a great resource for free.
>     * The CI pipeline should publish new file as a release, and do nothing on failure. I'm not sure if github actions have a standard place that shows logs; if so, it's sufficient to be able to see them.

Yes, we can see the logs from each run of the CI pipeline in GitHub actions.

When the CI pipeline succeeds, it creates a new draft release that you can to edit to provide more details about the release. But it creates a new draft release on each run, so you can end up having multiple draft releases if you push more than once to GitHub, as shown in the following image.
![Two drafts from two CI runs. Not neat](https://user-images.githubusercontent.com/20553476/95650131-6a262d80-0ad9-11eb-94fd-7d96fe9e896f.png)

That's not neat. We can separate the release process to run when you create a new tag, say v1.0. That will run the build process again and create the release. There are ways I can optimise that, but we can start from there. I need your opinion here. I'll open a PR today.

>     * The CI pipeline should use a bash script containing the commands to build the pdf file, rather than having those commands  directly embedded in a Dockerfile or somewhere else.

This suggestion is good. I've changed the setup to work this way. We can now pass command lines to the container and it will runs the commands.
 
> Please let me know how I can get the github to host the docker image for this build. I would expect to have a large image since it needs to contain LaTeX and LyX.

I've gone through their docs to understand how to set it up. It's quite simple, we'll work through it in a separate PR.

**Comment by winitzki** [comment]
@barisere  Yes, I think your suggestion is good - only push a release when there is a new tag. 

Please let me know how I can help further.

Once the basic build script works, I can edit the bash script.

One more question: I would like to publish several files in a release: a pdf file with the full draft, and a smaller pdf file with just the "clean" chapters. Is it possible to push more than one file to a release?

**Comment by barisere** [comment]
@winitzki All of these are possible. The tag check will require some research on my part, because I'm not very good at Bash scripting.
The basic build script works now. You can go ahead and edit the bash script. I'll give you access to my fork of the repo so that you can push changes there and trigger the pipeline. That will shorten the feedback cycle.
We can push several files in a release.
