### ISSUE TITLE
Small typo in binary search example (2.5.1.5)

### ISSUE THREAD

**Issue by miscenko** [winitzki/sofp#23]
Really enjoying reading this awesome book. Looks like there is a small typo in example 2.5.1.5 (page 50):
it says: target element is **x n with x i ≤ x n < x j−1**
but looks like it should be: **target element is x n with x i ≤ x n ≤ x j−1**

**Comment by winitzki** [comment]
Yes, you are right. I have corrected this mistake.

Thank you!

**Comment by miscenko** [comment]
Thank you for the book!
