### ISSUE TITLE
Link to PDF in readme.md gives a 404

### ISSUE THREAD

**Issue by Warwolt** [winitzki/sofp#25]
As of 2020-11-15, the following link to the PDF of the book is dead: https://github.com/winitzki/sofp/blob/master/sofp-src/sofp-draft.pdf

From this section of the readme: https://github.com/winitzki/sofp#printed-version-of-the-draft

I'm assuming this link should go to the current version of the draft?

**Comment by winitzki** [comment]
Thank you. Yes, the link need to be updated, will do now.
