### ISSUE TITLE
Broken link for sofp.pdf

### ISSUE THREAD

**Issue by atisvagyok** [winitzki/sofp#38]
It looks like the http://github.com/winitzki/sofp/blob/master/sofp-src/sofp.pdf link is broken which is referenced on the readme page and on https://sites.google.com/site/winitzki/sofp as well.

**Comment by winitzki** [comment]
Thank you. Yes, the link is old. The pdf file used to be checked into git but now it is no longer checked in but build by CI automatically on every master push. This means, unfortunately, that I do not have a permanent link to the PDF file. I will fix this at some point.
