### ISSUE TITLE
Download pdf file link missing(?).

### ISSUE THREAD

**Issue by pdelano** [winitzki/sofp#49]
From README.md:

The PDF version of the most recent master branch of the book can be downloaded by following the link to the PDF builds, clicking on the latest PDF build, and then clicking on "PDF files and LaTeX logs".

That didn't seem to work for me.  The text  "PDF files and LaTeX logs" doesn't seem to be linked to anything.  (For the older builds the link is expired.)

**Comment by winitzki** [comment]
I went to the latest build "adding new section of the LJT algorithm" and I see "PDF files and LaTeX logs" and it is a link to https://github.com/winitzki/sofp/suites/4699582922/artifacts/128511623  - do you not see this?

**Comment by pdelano** [comment]
It works fine for me now.  I do see the link and it downloads the file.
The previous build "Minor changes" works as well.  But an hour or so ago I
tried several times, with those builds and one or two others, without
results.  I suppose I could have done something wrong/stupid...

Well, nevermind, then.  Thanks for your extremely prompt attention.

**Comment by winitzki** [comment]
One thing is that you need to be logged in to github. If you were not logged in, you would not be able to download anything.

**Comment by pdelano** [comment]
Thanks, that was very likely my problem.  Sorry - I've downloaded lots of
stuff from github and I never knew I had to be logged in.  I suppose I'm
logged in to github most of the time.
