### ISSUE TITLE
There is a typo for exercise 2.1.7.8

### ISSUE THREAD

**Issue by allenjhan** [winitzki/sofp#59]
Hello,

I purchased a print copy of the book from Lulu that is the draft edition of the book as of December 29, 2021.

I have studied Exercise 2.1.7.8 and had to read it several times to understand what it is asking. Based upon my understanding, there appears to be a misprint that demands too much of the reader. We are told P = Boolean but Q = Set[Int]. I am not sure, but this should probably be revised to " P = Boolean and Q = Int." Both P and Q should either both refer to a primitive type or a collections type with a primitive type as a type parameter.

Moreover, if the variable q is of type Set[Int], the Scala compiler does not guarantee an ordering for the members of the set when performing operations on it. So I don't think you meant to say that q was a Set, unless this is some kind of trick question.

**Comment by winitzki** [comment]
Hi,

Thank you for your comment. There are no trick questions in the book. Why do you say that "both P and Q should either both refer to a primitive type or a collections type with a primitive type as a type parameter"? Why is there this restriction on what the types P and Q might be?

Yes, there is no ordering of the members of the set. Why is it necessary to have such an ordering?

I would certainly like to revise Exercise 2.1.7.8 to make it clearer. Could you tell me which sentence is difficult to understand?

> 
> Write the solution of Exercise 2.1.7.7 as a function with type parameters P and Q instead of the fixed types String and Int. 
> Test it with types P = Boolean and Q = Set[Int].

Did you solve Exercise 2.1.7.7 without difficulty?

**Comment by allenjhan** [comment]
Hello there.

After rereading the question with your comments in mind, I agree that the phrasing is unambiguous. I was confused because I was not sure whether p and q should have the types Seq[P] and Seq[Q], or just the types P and Q. I see now that the way the question is phrased makes it clear that p and q should have the types Seq[P] and Seq[Q]. I was thrown off because a set of Int is something one does not see used often as a key for a map. I am not sure if this is necessary, but it might be helpful to amend the text so that it is explicitly stated that the return value of the computation is of type Map[Q, P]. However, if you think determining the correct return type is part of the question, and so the wording of the question should remain unchanged, I will not complain.

**Comment by allenjhan** [comment]
Hi, I am reopening the issue so you have a visible reminder to amend the problem and make it more clear if you feel that is necessary. Otherwise, feel free to close the issue again.

**Comment by winitzki** [comment]
I will add the comment that the return value must have type Map[Q, P].
