### ISSUE TITLE
Either doesn't have a filter method

### ISSUE THREAD

**Issue by hagl** [winitzki/sofp#6]
Section `3.2.3 Standard disjunctive types: Option, Either, Try` claims that Either defines a `.filter` method, but in Scala 2.12 and 2.13 there is only a `.filterOrElse` on the Either type.

Thank you very much for creating this book! Is it ok to provide feedback like the above as github issues, or would you prefer a different channel?

**Comment by winitzki** [comment]
Thank you! Creating github issues are fine.

**Comment by winitzki** [comment]
I'll remove the mention of `filter` from that place.

**Comment by winitzki** [comment]
@hagl I'm closing this issue after fixing the text. Please open other issues and/or PRs whenever you find something that doesn't make sense. Thank you!

**Comment by hagl** [comment]
Thanks! I'll open new issues, if I find anything else.

**Comment by winitzki** [comment]
@hagl  If you continue to read the book, I'd appreciate if you let me know how you perceive chapters 4, 5, 6 compared with chapters 1, 2, 3 as regards the complexity of the material.
