### ISSUE TITLE
Invalid proof on page 39 of 12-29-2021 edition

### ISSUE THREAD

**Issue by allenjhan** [winitzki/sofp#60]
Hello there,

I have the draft version as of December 29, 2021.

On page 39, there is a proof of equation 2.4 that has a flaw. It uses equation 2.4 to show that

`d([x]) ++ s) * 10 + y = (x * 10^|s| + d(s)) * 10 + y`

However, since equation 2.4 is what is to be proved, we cannot assume equation 2.4 as a property when attempting to prove equation 2.4. Doing so is the fallacy of begging the question.

I hope I am not misunderstanding something here.

**Comment by allenjhan** [comment]
I just want to add that I'm really enjoying the book so far, and that I really appreciate all the effort you put into it.

**Comment by winitzki** [comment]
The proof of Eq. (2.4) is by the method of "mathematical induction". We first prove that Eq. (2.4) holds for an empty sequence s. Then we assume that Eq. (2.4) holds for some sequence `s` and then prove that it also holds for a larger sequence `s ++ [y]`. In this way, we will have proved that Eq. (2.4) holds for all sequences. Are you familiar with proofs by induction?

**Comment by allenjhan** [comment]
Hello there,

Thank you for patiently correcting me on this point. I am familiar with proof by induction, but it's clear I do not know it as well as I thought.

In fact, in the text, you state that "The inductive step assumes Eq. (2.4) for a given x and a given sequence s, and needs to prove that for any y, the same property holds with s++[y] instead of s."

Again, thanks, I will try to be more careful going forwards.
