### ISSUE TITLE
Possible typo in section 9.2.1

### ISSUE THREAD

**Issue by mcwitt** [winitzki/sofp#66]
In section 9.2.1, "Simplifying the filtering laws: Motivation for `deflate`":

> For example, if $F^{A}\triangleq\mathbb 1+A$, the filtering operation may remove the value of type $A$ and return the result $1+\mathbb 0$. It appears that the filtering operation, at the type level, replaces the type $A$ by the unit type $\mathbb 1$ whenever a value does not pass the filtering condition. In examples of non-filterable functors $F$, such as $F^{A}\triangleq A\times\left(\mathbb 1+A\right)$, the type expression for $F^{A}$ cannot accommodate replacing the type $A$ by $\mathbb 1$. 

should

> replaces the type $A$ by the unit type $\mathbb 1$ whenever a value does not pass the filtering condition

be instead "replaces the type $A$ by the **void type $\mathbb 0$** whenever a value does not pass the filtering condition", and

> In examples of non-filterable functors $F$, such as $F^{A}\triangleq A\times\left(\mathbb 1+A\right)$, the type expression for $F^{A}$ cannot accommodate replacing the type $A$ by $\mathbb 1$.

be instead "In examples of non-filterable functors $F$, such as $F^{A}\triangleq A\times\left(\mathbb 1+A\right)$, the type expression for $F^{A}$ cannot accommodate replacing the type $A$ by **$\mathbb 0$**"?

**Comment by winitzki** [comment]
Thank you! I will have to think about how to rewrite that. I actually meant to say what it says, I did not mean to use 𝟘 - so this is not a typo in the book. But you propose a motivation based on "replacing $A$ by 𝟘", and this is interesting and perhaps more clear than what I had in mind.

**Comment by winitzki** [comment]
PR is merged with a correction.
