### ISSUE TITLE
Section 7.1.2

### ISSUE THREAD

**Issue by greenbergjosh** [winitzki/sofp#7]
I have reached chapter 7.  It is an excellent review and it might be worth informing the reader of it's existence at some earlier point.  Reading through the prior material I sometimes got stuck on notation, but your exposition in chapter 7 helped clarify some sticking points.

I do have a question in section 7.1.2 related to the expression

(x → t ⊲ f ) ; g = x → (t ⊲ f ⊲ g) = x → t ⊲ f ; g

Please excuse the fact that the triangles got flipped.  They are all backwards but all in the right places.

I think the right way to look at this is

(x → (t ⊲ f) ) ; g = x → (t ⊲ f ⊲ g) = x → t ⊲ f ; g

where f is a function that takes a t and returns a function that takes an x.

I initially saw it as

((x → t) ⊲ f ) ; g = x → (t ⊲ f ⊲ g) = x → t ⊲ f ; g

which doesn't make sense in the context of the rest of the expression since we could not pull off the t, as in t ⊲ f.  I just thought, assuming I am understanding correctly myself, that it might be useful to mention the precedence or grouping rules of → versus ⊲.  I think I recall some mention of that much earlier in the book, but given chapter 7 as a review of notation, I thought it might be a good place to mention it.

**Comment by winitzki** [comment]
Thank you. Yes, the correct way to read the notation x→ t▷f  is x→ (t▷f). I am not sure where I said that in the book, but I'll add it both in chapter 7 and earlier.

I am not sure that it would be useful to read chapter 7 before chapters 5 and 6. There are not enough examples in chapter 5 alone; chapter 6, on the other hand, already needs a lot of notation, so I think chapter 6 is a good place to introduce all that notation for the first time, and then chapter 7 to review all of it.

**Comment by winitzki** [comment]
I added some more comments about the precedence of the pipe operation, before section 6.3 and in chapter 7, section 7.1.2.

**Comment by winitzki** [comment]
Did you have any trouble getting through chapters 5 and 6? These chapters introduce material that's significantly more difficult than the stuff in previous chapters. I'm interested in your feedback about that.

Right now I'm working on chapter 9, which will be about the same difficulty as chapter 8.

**Comment by greenbergjosh** [comment]
Other than a few points where I got stuck on notation, I think 5 and 6 were very understandable, and most notational issues were clarified in chapter 7.  Truly, I think your 5 and 6 were the most lucid explanation of CH that I have read to date.  To be fair, however, some of the other texts just moved through the material much more quickly and were far more theoretical.  In your text, I like how you consistently display both scala code and type notation.  For me, notational magic (as in, let's use the name of the functor to represent the identity natural transformation but let's keep that a secret and not mention that notational device anywhere) and application (as in, how does this apply to anything) have always been a bit of an issue.  You have successfully bypassed much of that by consistently using code, example applications, and type notation. Its a pleasure to read as each presentation helps solidify the other.  I really liked your explanation of the law of the excluded middle.  When looking at introductory material on homotopy type theory, the authors often mention this in relation to constructive logic, but they rarely make it clear.  I would love to see you get into J (from type theory) and into natural transformations.  Maybe I just haven't reached those chapters yet.  I do plan on finishing your book and then reading it again.  I will hopefully have some more concrete feedback on the second read. 

I am presently reading section 8.3.1, and I did have a few comments.  This was the first time in your book where I lost a sense of why.  You are building something (extractors) for some reason, but I don't quite know the reason (though you mention serializers and show at the end).  I am suspending disbelief and hoping that the purpose will become clear as I continue through the subsequent sections.  At the risk of making the section far too long, it may be worth showing how the extractors can be effectively used and how they are better than some other alternative.  Perhaps, that belongs in an appendix since it would likely be too long for the body of the text.  More importantly, however, rather than focusing on how to use extractors, I would be interested to better understand why you chose extractors as the example.  I feel that you are building up to something, maybe moving towards some better abstraction of which extractors is simply one instance.  Alternatively, maybe you are showing how to construct a new concept by using the building blocks (e.g. products, co-products, function types, etc).  If that is the case, perhaps a higher level explanation of that pattern - how to construct something from the building blocks, why it is valuable, and what result we hope to achieve would be helpful.  If that continuity is there (and it may well be), I likely lost it while working my way through the details of the material.  To use a trite idiom, I lost the forest for the trees when I hit extractors.  I read the section a few times, I think I understand each tree, but I have lost my sense of direction.

Finally, in regards to one particular tree, I have an extra comment.  The idea of expanded functions allowing recursion to terminate sat very well in my gut, but not as well in my head.  In other words I didn't have any doubts about what you were saying, but I still wanted a prettier picture of it in my brain.  I fiddled a bit:

def k(f: Int => Int): Int => Int = 
{ 
  x => if (x <= 0) 1 else 2 * f(x - 1) 
} 
def f_bad: Int => Int = k(f_bad) 
def f:     Int => Int = { x => k(f)(x) } 

println(((x:Int) => if (x <= 0) 1 else 2 * (x => k(f)(x))(x - 1) )(1))
println(2* (x => k(f)(x))(0))
println(((x:Int) => if (x <= 0) 1 else 2 * (x => k(f)(x))(x - 1) )(0))

//println(f_bad)
println(f)


The expansions (kind of what I meant before when I mentioned the way things are often illustrated when teaching lambda calculus) helped me understand what was running.  Still, however, it just didn't feel completely clear.  So, the simple println(f_bad) and println(f) finally got me there.  You state "so k( f ) is evaluated only when f is applied to an argument".  That's the gut feel, but seeing println(f_bad) blow the stack, and println(f) just tell me its a function brought it home.  Unfortunately, before reading your book, I never looked at anything in Scala, so I suspect that is also playing a factor.

Thank you for the continued conversation.  I am looking forward to the remainder of the book.

**Comment by winitzki** [comment]
Thank you for extended explanations. I am traveling right now and will have to answer you in more detail a bit later. Just a few quick answers for now:

1. "Extractors" are just an example of a typeclass, not very deep but useful. All typeclasses in chapter 8 are simple and are more for illustrating the method of "structural analysis" where you derive typeclass instances.
2. Scala has a bit of difficulty with "implicits". The new Scala 3 will have a different system of implicits, with its own problems. However, it was not my intention to make the exposition hard to understand. I will have to revisit the way I explain Scala's "implicits" and where they enter the picture. We can do exactly the same things without implicits - it will just be longer code.
