### ISSUE TITLE
Small variable name error in Exercise 1.6.1.4

### ISSUE THREAD

**Issue by darrylkid** [winitzki/sofp#74]
![image](https://github.com/winitzki/sofp/assets/28680908/399eb68b-aafd-4e89-afe6-5b88eff86f5a)

The bound variable in the product reduction is in terms of $k$ but the term $\frac{1}{1 - \frac{1}{p^4}}$ is in terms of $p$. The bound variables should match each other here, not be different. 

This comes from the latest Nov 23, 2023 draft.

**Comment by winitzki** [comment]
Thank you, I will fix this in the next version!
