### ISSUE TITLE
 Example 2.2.5.1 possible extension

### ISSUE THREAD

**Issue by andreas-roehler** [winitzki/sofp#85]
The solution of Example 2.2.5.1 employs builtin math.max.
It might be useful, to display a more iconic form too, like

`def foldleftMax(s: Seq[Int]): Int = s.foldLeft(Int.MinValue) { (x, y) => if (x > y) x else y }
`
scala>` foldleftMax(List(-1, -4, -6, -2))`
res1: Int = -1

**Comment by winitzki** [comment]
Thank you, I will add this to the text.
