### ISSUE TITLE
opportunity to mention 'init' function

### ISSUE THREAD

**Issue by philipschwarz** [winitzki/sofp#97]
Hello Sergei,

When the book [defines](https://github.com/winitzki/sofp/blob/master/sofp-src/tex/sofp-induction.tex#L1353) `digitsToInt`, there could be an opportunity, either to replace `s.take(s.length - 1)` with `s.init`, or, if using `s.take(s.length - 1)` serves an essential purpose for the didactic objectives of this chapter, at least to mention the existence of the `init` function, maybe in a footnote, or the like (maybe it could mention how splitting a list using `last` and `init` is 'the opposite' of splitting it using `head` and `tail`).

```Scala
def digitsToInt(s: Seq[Int]): Int = if (s.isEmpty) 0 else {
  val x = s.last                 // To split s = xs :+ x, compute x
  val xs = s.take(s.length - 1)  // and xs.
  digitsToInt(xs) * 10 + x       // Call digitsToInt(...) recursively.
}
```

Apologies if `init` is already mentioned elsewhere in the book: when this idea occurred to me I was just dipping back into sections of this chapter, not looking at the whole book.

**Comment by winitzki** [comment]
Hello Philip,

No, I don't think I mention `init` in the book yet. Perhaps it's a good opportunity to do so.

**Comment by winitzki** [comment]
I have updated Part I of the book, which is probably now ready for publication.

**Comment by philipschwarz** [comment]
I have updated Part I of the book
🙌
which is probably now ready for publication.
🤩
